### ISSUE TITLE
use datetime2 instead of datetime

### ISSUE THREAD

**Issue by viktoriasee** [charlesbaynham/gitver#2]
This is a small issue. When I install `gitver` I had to install the deprecated `datetime` which is not used by any package I currently use. Could you switch to the newer `datetime2` in order to keep the requirements for new package installations low?

**Comment by charlesbaynham** [comment]
Nice idea! That's completed by 7c72eeb2 and uploaded to CTAN.

**Comment by Epaulard** [comment]
Just a kind remark.
There's still a reference to datetime in the [CTAN description](https://www.ctan.org/pkg/gitver) of the package.
"The package requires hyperref, catchfile, pdftexcmds, and **datetime**."

**Comment by charlesbaynham** [comment]
@Epaulard thanks for spotting that, it's actually because the version on CTAN is still version 1.1 which actually does use `datetime`. Seems like I forgot to reply to an email so it didn't get uploaded properly... I've done that now, so hopefully it'll be up soon.

**Comment by Epaulard** [comment]
Thanks a lot !

**Comment by charlesbaynham** [comment]
Up on CTAN now
