### ISSUE TITLE
Git command failed 

### ISSUE THREAD

**Issue by Epaulard** [charlesbaynham/gitver#3]
Thanks a lot for this package.

"git describe --match nopenopenope --always --long --dirty --abbrev=6" is working fine with gitbash.
Unfortunately I've got an error message when using \gitVer with lualatex -shell-escape and the following code 

\documentclass{article}
\usepackage[noheader,nopdfinfo]{gitver}

\begin{document}
\gitVer
 
\end{document}
Attached .aux and .log
[LuaExo.log](https://github.com/charlesbaynham/gitver/files/5447732/LuaExo.log)

\relax 
\providecommand\hyper@newdestlabel[2]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\HyperFirstAtBeginDocument{\ifx\hyper@anchor\@undefined
\global\let\oldcontentsline\contentsline
\gdef\contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\global\let\oldnewlabel\newlabel
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\AtEndDocument{\ifx\hyper@anchor\@undefined
\let\contentsline\oldcontentsline
\let\newlabel\oldnewlabel
\fi}
\fi}
\global\let\hyper@last\relax 
\gdef\HyperFirstAtBeginDocument#1{#1}
\providecommand\HyField@AuxAddToFields[1]{}
\providecommand\HyField@AuxAddToCoFields[2]{}
\gdef \@abspage@last{1}

**Comment by charlesbaynham** [comment]
Morning Epaulard,

Is there anything in the file LuaExo_desc.aux?

Cheers,
C

Sent from my phone; please excuse typos or brevity.

________________________________

**Comment by Epaulard** [comment]
Yes there is the following 

\relax
\providecommand\hyper@newdestlabel[2]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\HyperFirstAtBeginDocument{\ifx\hyper@anchor@undefined
\global\let\oldcontentsline\contentsline
\gdef\contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\global\let\oldnewlabel\newlabel
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\AtEndDocument{\ifx\hyper@anchor@undefined
\let\contentsline\oldcontentsline
\let\newlabel\oldnewlabel
\fi}
\fi}
\global\let\hyper@last\relax
\gdef\HyperFirstAtBeginDocument#1{#1}
\providecommand\HyField@AuxAddToFields[1]{}
\providecommand\HyField@AuxAddToCoFields[2]{}
\gdef @ABSPage@last{1}

**Comment by charlesbaynham** [comment]
That looks like the contents of `LuaExo.aux`: I'm looking for `LuaExo_desc.aux`!

**Comment by Epaulard** [comment]
My mistake. Sorry
There's no LuaExo_desc.aux file
Cheers

**Comment by charlesbaynham** [comment]
Hmm ok, this file ought to be created when you compile. Could you check that git is accessible from the normal Windows command prompt, not just from git bash? Also, could you try compiling with `pdflatex --shell-escape LuaExo.tex` to see if it's related to lualatex.

**Comment by Epaulard** [comment]
Same error from  normal Windows command prompt.
Working **fine** with pdflatex --shell-escape LuaExo.tex.

**Comment by charlesbaynham** [comment]
The fact that it works with pdflatex is quite surprising, but if the git command fails from a normal Windows command prompt then that'll be the issue. Can you try adding git to your system PATH?

**Comment by charlesbaynham** [comment]
> Same error from normal Windows command prompt.

Sorry, to clarify: did you run `laulatex --shell-escape LuaExo.tex` or did you attempt to run git directly, e.g. via `git status`. I meant the latter.

**Comment by Epaulard** [comment]
I run lualatex --shell-escape LuaExo.tex and \gitVer fails
I run pdflatex --shell-escape LuaExo.tex and  \gitVer returns the correct output

**Comment by charlesbaynham** [comment]
Yes, I can reproduce this on my machine. I'll look into it

**Comment by charlesbaynham** [comment]
This seems to be an issue with the `article` document class. This works:

```
\documentclass{standalone}
\usepackage{gitver}

\begin{document}
Hello world! Version: \gitVer{}

\end{document}
```

whereas this fails:

```
\documentclass{article}
\usepackage{gitver}

\begin{document}
Hello world! Version: \gitVer{}

\end{document}
```

**Comment by charlesbaynham** [comment]
In fact, I can reproduce with just

```
\documentclass{article}

\begin{document}

Test

\write18{echo SHELL ENABLED > out.txt}

\end{document}
```

So no gitver at all

**Comment by charlesbaynham** [comment]
Turns out that lualatex removes the `\write18` command which gitver uses. I've updated it to supports lualatex in v1.3 now, on its way to CTAN. In the mean time you can download the `gitver.sty` file from this repository directly and place it next to your project to use the new version.

**Comment by Epaulard** [comment]
Understood. Thanks a lot for investigating this. I use lualuatex and article class for some years but did not face this issue yet.
